//! Raw FFI bindings to the vendored `isom_capi` static library (C ABI shim over
//! the isom-poc map engine). Generated by bindgen at build time; this crate is a
//! `-sys` crate only — the safe `Result`-returning wrapper lives in the separate
//! `isom` crate.
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

/// Force the linker to retain `isom_capi.lib` for crates that depend on this one.
///
/// A `-sys` crate that merely *declares* `extern "C"` fns (never calling them
/// inside its own rlib) lets rustc prune the native library from the link
/// requirements it propagates to downstream binaries — the symbol then comes up
/// `LNK2019` in dependents. Referencing one symbol from a `#[used]` static keeps
/// the dependency edge live so `cargo:rustc-link-lib=static=isom_capi` reaches the
/// final link of every consumer (the safe `isom` wrapper, `src-tauri`, and the
/// `tests/ffi_smoke.rs` integration test here).
#[doc(hidden)]
#[used]
pub static __ISOM_LINK_ANCHOR: unsafe extern "C" fn() -> ::std::os::raw::c_int =
    isom_abi_version;

#[cfg(test)]
mod tests {
    use super::*;

    /// The bindgen-generated `isom_abi_version` links against the static lib and
    /// returns ISOM_ABI_VERSION (== 1). Proves the C lib built + linked and the
    /// bindings match the header. This lives in-crate (not only in tests/) so the
    /// build-script `cargo:rustc-link-lib=static=isom_capi` directive applies to
    /// the same compilation unit.
    #[test]
    fn abi_version_is_one() {
        assert_eq!(unsafe { isom_abi_version() }, ISOM_ABI_VERSION as i32);
    }
}
